const customers = [
    {	CustomerID: "ALFKI",	CompanyName: "Alfreds Futterkiste",	ContactName: "Maria Anders",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "ANATR",	CompanyName: "Ana Trujillo Emparedados y helados",	ContactName: "Ana Trujillo",	ContactTitle: "Owner"	},
    {	CustomerID: "ANTON",	CompanyName: "Antonio Moreno Taquería",	ContactName: "Antonio Moreno",	ContactTitle: "Owner"	},
    {	CustomerID: "AROUT",	CompanyName: "Around the Horn",	ContactName: "Thomas Hardy",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "BERGS",	CompanyName: "Berglunds snabbköp",	ContactName: "Christina Berglund",	ContactTitle: "Order Administrator"	},
    {	CustomerID: "BLAUS",	CompanyName: "Blauer See Delikatessen",	ContactName: "Hanna Moos",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "BLONP",	CompanyName: "Blondel père et fils",	ContactName: "Frédérique Citeaux",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "BOLID",	CompanyName: "Bólido Comidas preparadas",	ContactName: "Martín Sommer",	ContactTitle: "Owner"	},
    {	CustomerID: "BONAP",	CompanyName: "Bon app'",	ContactName: "Laurence Lebihan",	ContactTitle: "Owner"	},
    {	CustomerID: "BOTTM",	CompanyName: "Bottom-Dollar Markets",	ContactName: "Elizabeth Lincoln",	ContactTitle: "Accounting Manager"	},
    {	CustomerID: "BSBEV",	CompanyName: "B's Beverages",	ContactName: "Victoria Ashworth",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "CACTU",	CompanyName: "Cactus Comidas para llevar",	ContactName: "Patricio Simpson",	ContactTitle: "Sales Agent"	},
    {	CustomerID: "CENTC",	CompanyName: "Centro comercial Moctezuma",	ContactName: "Francisco Chang",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "CHOPS",	CompanyName: "Chop-suey Chinese",	ContactName: "Yang Wang",	ContactTitle: "Owner"	},
    {	CustomerID: "COMMI",	CompanyName: "Comércio Mineiro",	ContactName: "Pedro Afonso",	ContactTitle: "Sales Associate"	},
    {	CustomerID: "CONSH",	CompanyName: "Consolidated Holdings",	ContactName: "Elizabeth Brown",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "DRACD",	CompanyName: "Drachenblut Delikatessen",	ContactName: "Sven Ottlieb",	ContactTitle: "Order Administrator"	},
    {	CustomerID: "DUMON",	CompanyName: "Du monde entier",	ContactName: "Janine Labrune",	ContactTitle: "Owner"	},
    {	CustomerID: "EASTC",	CompanyName: "Eastern Connection",	ContactName: "Ann Devon",	ContactTitle: "Sales Agent"	},
    {	CustomerID: "ERNSH",	CompanyName: "Ernst Handel",	ContactName: "Roland Mendel",	ContactTitle: "Sales Manager"	},
    {	CustomerID: "FAMIA",	CompanyName: "Familia Arquibaldo",	ContactName: "Aria Cruz",	ContactTitle: "Marketing Assistant"	},
    {	CustomerID: "FISSA",	CompanyName: "FISSA Fabrica Inter. Salchichas S.A.",	ContactName: "Diego Roel",	ContactTitle: "Accounting Manager"	},
    {	CustomerID: "FOLIG",	CompanyName: "Folies gourmandes",	ContactName: "Martine Rancé",	ContactTitle: "Assistant Sales Agent"	},
    {	CustomerID: "FOLKO",	CompanyName: "Folk och fä HB",	ContactName: "Maria Larsson",	ContactTitle: "Owner"	},
    {	CustomerID: "FRANK",	CompanyName: "Frankenversand",	ContactName: "Peter Franken",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "FRANR",	CompanyName: "France restauration",	ContactName: "Carine Schmitt",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "FRANS",	CompanyName: "Franchi S.p.A.",	ContactName: "Paolo Accorti",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "FURIB",	CompanyName: "Furia Bacalhau e Frutos do Mar",	ContactName: "Lino Rodriguez",	ContactTitle: "Sales Manager"	},
    {	CustomerID: "GALED",	CompanyName: "Galería del gastrónomo",	ContactName: "Eduardo Saavedra",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "GODOS",	CompanyName: "Godos Cocina Típica",	ContactName: "José Pedro Freyre",	ContactTitle: "Sales Manager"	},
    {	CustomerID: "GOURL",	CompanyName: "Gourmet Lanchonetes",	ContactName: "André Fonseca",	ContactTitle: "Sales Associate"	},
    {	CustomerID: "GREAL",	CompanyName: "Great Lakes Food Market",	ContactName: "Howard Snyder",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "GROSR",	CompanyName: "GROSELLA-Restaurante",	ContactName: "Manuel Pereira",	ContactTitle: "Owner"	},
    {	CustomerID: "HANAR",	CompanyName: "Hanari Carnes",	ContactName: "Mario Pontes",	ContactTitle: "Accounting Manager"	},
    {	CustomerID: "HILAA",	CompanyName: "HILARIÓN-Abastos",	ContactName: "Carlos Hernández",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "HUNGC",	CompanyName: "Hungry Coyote Import Store",	ContactName: "Yoshi Latimer",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "HUNGO",	CompanyName: "Hungry Owl All-Night Grocers",	ContactName: "Patricia McKenna",	ContactTitle: "Sales Associate"	},
    {	CustomerID: "ISLAT",	CompanyName: "Island Trading",	ContactName: "Helen Bennett",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "KOENE",	CompanyName: "Königlich Essen",	ContactName: "Philip Cramer",	ContactTitle: "Sales Associate"	},
    {	CustomerID: "LACOR",	CompanyName: "La corne d'abondance",	ContactName: "Daniel Tonini",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "LAMAI",	CompanyName: "La maison d'Asie",	ContactName: "Annette Roulet",	ContactTitle: "Sales Manager"	},
    {	CustomerID: "LAUGB",	CompanyName: "Laughing Bacchus Wine Cellars",	ContactName: "Yoshi Tannamuri",	ContactTitle: "Marketing Assistant"	},
    {	CustomerID: "LAZYK",	CompanyName: "Lazy K Kountry Store",	ContactName: "John Steel",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "LEHMS",	CompanyName: "Lehmanns Marktstand",	ContactName: "Renate Messner",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "LETSS",	CompanyName: "Let's Stop N Shop",	ContactName: "Jaime Yorres",	ContactTitle: "Owner"	},
    {	CustomerID: "LILAS",	CompanyName: "LILA-Supermercado",	ContactName: "Carlos González",	ContactTitle: "Accounting Manager"	},
    {	CustomerID: "LINOD",	CompanyName: "LINO-Delicateses",	ContactName: "Felipe Izquierdo",	ContactTitle: "Owner"	},
    {	CustomerID: "LONEP",	CompanyName: "Lonesome Pine Restaurant",	ContactName: "Fran Wilson",	ContactTitle: "Sales Manager"	},
    {	CustomerID: "MAGAA",	CompanyName: "Magazzini Alimentari Riuniti",	ContactName: "Giovanni Rovelli",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "MAISD",	CompanyName: "Maison Dewey",	ContactName: "Catherine Dewey",	ContactTitle: "Sales Agent"	},
    {	CustomerID: "MEREP",	CompanyName: "Mère Paillarde",	ContactName: "Jean Fresnière",	ContactTitle: "Marketing Assistant"	},
    {	CustomerID: "MORGK",	CompanyName: "Morgenstern Gesundkost",	ContactName: "Alexander Feuer",	ContactTitle: "Marketing Assistant"	},
    {	CustomerID: "NORTS",	CompanyName: "North/South",	ContactName: "Simon Crowther",	ContactTitle: "Sales Associate"	},
    {	CustomerID: "OCEAN",	CompanyName: "Océano Atlántico Ltda.",	ContactName: "Yvonne Moncada",	ContactTitle: "Sales Agent"	},
    {	CustomerID: "OLDWO",	CompanyName: "Old World Delicatessen",	ContactName: "Rene Phillips",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "OTTIK",	CompanyName: "Ottilies Käseladen",	ContactName: "Henriette Pfalzheim",	ContactTitle: "Owner"	},
    {	CustomerID: "PARIS",	CompanyName: "Paris spécialités",	ContactName: "Marie Bertrand",	ContactTitle: "Owner"	},
    {	CustomerID: "PERIC",	CompanyName: "Pericles Comidas clásicas",	ContactName: "Guillermo Fernández",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "PICCO",	CompanyName: "Piccolo und mehr",	ContactName: "Georg Pipps",	ContactTitle: "Sales Manager"	},
    {	CustomerID: "PRINI",	CompanyName: "Princesa Isabel Vinhos",	ContactName: "Isabel de Castro",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "QUEDE",	CompanyName: "Que Delícia",	ContactName: "Bernardo Batista",	ContactTitle: "Accounting Manager"	},
    {	CustomerID: "QUEEN",	CompanyName: "Queen Cozinha",	ContactName: "Lúcia Carvalho",	ContactTitle: "Marketing Assistant"	},
    {	CustomerID: "QUICK",	CompanyName: "QUICK-Stop",	ContactName: "Horst Kloss",	ContactTitle: "Accounting Manager"	},
    {	CustomerID: "RANCH",	CompanyName: "Rancho grande",	ContactName: "Sergio Gutiérrez",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "RATTC",	CompanyName: "Rattlesnake Canyon Grocery",	ContactName: "Paula Wilson",	ContactTitle: "Assistant Sales Representative"	},
    {	CustomerID: "REGGC",	CompanyName: "Reggiani Caseifici",	ContactName: "Maurizio Moroni",	ContactTitle: "Sales Associate"	},
    {	CustomerID: "RICAR",	CompanyName: "Ricardo Adocicados",	ContactName: "Janete Limeira",	ContactTitle: "Assistant Sales Agent"	},
    {	CustomerID: "RICSU",	CompanyName: "Richter Supermarkt",	ContactName: "Michael Holz",	ContactTitle: "Sales Manager"	},
    {	CustomerID: "ROMEY",	CompanyName: "Romero y tomillo",	ContactName: "Alejandra Camino",	ContactTitle: "Accounting Manager"	},
    {	CustomerID: "SANTG",	CompanyName: "Santé Gourmet",	ContactName: "Jonas Bergulfsen",	ContactTitle: "Owner"	},
    {	CustomerID: "SAVEA",	CompanyName: "Save-a-lot Markets",	ContactName: "Jose Pavarotti",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "SEVES",	CompanyName: "Seven Seas Imports",	ContactName: "Hari Kumar",	ContactTitle: "Sales Manager"	},
    {	CustomerID: "SIMOB",	CompanyName: "Simons bistro",	ContactName: "Jytte Petersen",	ContactTitle: "Owner"	},
    {	CustomerID: "SPECD",	CompanyName: "Spécialités du monde",	ContactName: "Dominique Perrier",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "SPLIR",	CompanyName: "Split Rail Beer & Ale",	ContactName: "Art Braunschweiger",	ContactTitle: "Sales Manager"	},
    {	CustomerID: "SUPRD",	CompanyName: "Suprêmes délices",	ContactName: "Pascale Cartrain",	ContactTitle: "Accounting Manager"	},
    {	CustomerID: "THEBI",	CompanyName: "The Big Cheese",	ContactName: "Liz Nixon",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "THECR",	CompanyName: "The Cracker Box",	ContactName: "Liu Wong",	ContactTitle: "Marketing Assistant"	},
    {	CustomerID: "TOMSP",	CompanyName: "Toms Spezialitäten",	ContactName: "Karin Josephs",	ContactTitle: "Marketing Manager"	},
    {	CustomerID: "TORTU",	CompanyName: "Tortuga Restaurante",	ContactName: "Miguel Angel Paolino",	ContactTitle: "Owner"	},
    {	CustomerID: "TRADH",	CompanyName: "Tradição Hipermercados",	ContactName: "Anabela Domingues",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "TRAIH",	CompanyName: "Trail's Head Gourmet Provisioners",	ContactName: "Helvetius Nagy",	ContactTitle: "Sales Associate"	},
    {	CustomerID: "VAFFE",	CompanyName: "Vaffeljernet",	ContactName: "Palle Ibsen",	ContactTitle: "Sales Manager"	},
    {	CustomerID: "VICTE",	CompanyName: "Victuailles en stock",	ContactName: "Mary Saveley",	ContactTitle: "Sales Agent"	},
    {	CustomerID: "VINET",	CompanyName: "Vins et alcools Chevalier",	ContactName: "Paul Henriot",	ContactTitle: "Accounting Manager"	},
    {	CustomerID: "WANDK",	CompanyName: "Die Wandernde Kuh",	ContactName: "Rita Müller",	ContactTitle: "Sales Representative"	},
    {	CustomerID: "WARTH",	CompanyName: "Wartian Herkku",	ContactName: "Pirkko Koskitalo",	ContactTitle: "Accounting Manager"	},
    {	CustomerID: "WELLI",	CompanyName: "Wellington Importadora",	ContactName: "Paula Parente",	ContactTitle: "Sales Manager"	},
    {	CustomerID: "WHITC",	CompanyName: "White Clover Markets",	ContactName: "Karl Jablonski",	ContactTitle: "Owner"	},
    {	CustomerID: "WILMK",	CompanyName: "Wilman Kala",	ContactName: "Matti Karttunen",	ContactTitle: "Owner/Marketing Assistant"	},
    {	CustomerID: "WOLZA",	CompanyName: "Wolski  Zajazd",	ContactName: "Zbyszek Piestrzeniewicz",	ContactTitle: "Owner"	}
]

module.exports = customers